version: '3'

services:
  dev-container:
    image: secure-coding:latest 
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app