version: '3'

services:
  dev-container:
    image: secure-coding:latest 
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - "TERM=xterm-256color"